version: '3'
services:
  mosquitto:
    #image: "monster1025/alpine86-mosquitto:latest"
    build: ./mosquitto/docker
    container_name: mosquitto
    env_file: ./mosquitto/settings/mqtt.env
    ports:
      - "1883:1883"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 50m 

  home:
   #image: monster1025/yandex-ddns
   build: ./ddns/docker
   env_file: ./ddns/settings/token.env
   environment:
     - SUBDOMAIN="home-alt"
   restart: always

  hass:
    image: homeassistant/home-assistant:latest #0.100.3
    container_name: hass
    volumes:
      - ./hass/settings:/config
      #- ./hass/settings/hosts.txt:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
      - "9898:9898/udp"
      - "4321:4321/udp"
      - "51827:51827" #Homekit
    depends_on:
    #  - mysql
     - mosquitto
    #  - broadlink
    network_mode: "host"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: 30s
      timeout: 10s
      retries: 6
    logging:
      driver: json-file
      options:
        max-size: 50m
        
  appdaemon:
    build:
      context: ./appdaemon/docker
    container_name: appdaemon
    depends_on:
      - hass
    volumes:
      - ./appdaemon/settings:/conf
      - ./hass/settings/secrets.yaml:/conf/secrets.yaml:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    links:
      - "hass"
    logging:
      driver: json-file
      options:
          max-size: "10m"
          max-file: "5"


  esphome:
    image: esphome/esphome-armv7
    container_name: esphome
    ports:
      - "6052:6052"
    volumes:
      - ./esphome/settings:/config
      - ./hass/settings/secrets.yaml:/config/secrets.yaml:ro
    network_mode: "host"
    logging:
      driver: json-file
      options:
          max-size: "10m"
          max-file: "5"

  rass:
    build:
      context: ./rass/docker
      dockerfile: Dockerfile-rpi
    container_name: rass
    network_mode: host
    env_file: 
     - ./mosquitto/settings/mqtt.env
     # - ./rass/settings/rass.env
    environment:
      AUTO_DISCOVERY: true
      # - LOGGER=true
      # - LOGLEVEL=info
      # - SERVICES=ble,mqtt
      # - ROOM=balcony
      # - MQTT_URL=mqtt://192.168.1.6
      # - MQTT_REJECT_UNAUTHORIZED=true
      # - AUTO_DISCOVERY=true
      # - BLE_CHANNEL=home/presence
      # - BLE_USE_ADDRESS=false
      # - BLE_WHITELIST=['c339570b5315','1862e411fd87']
    restart: always
    logging:
      driver: json-file
      options:
          max-size: "10m"
          max-file: "5"