homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 124
  unit_system: metric
  time_zone: !secret timezone
  packages: !include_dir_named packages

logger:
  default: info
  logs:
    custom_components.yandex_smart_home: debug
    icloud: debug

api:

http:
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.19.0.0/24
    - 172.18.0.0/24

mobile_app:

# Enables the frontend
frontend:
lovelace:
  mode: yaml
    
# Enables configuration UI
config:
discovery:
system_health:

# # Enables support for tracking state changes over time
history:
logbook: