homekit:
  auto_start: False
  filter:
    include_domains:
      - alarm_control_panel
      - switch
      - light
      - vacuum
      - cover
      - fan
      - climate
      - camera
    include_entities:
      # - sensor.humidity_158d0001149b3c
      # - sensor.humidity_158d000117d37a
      # - sensor.humidity_158d00012d9ad7
      # - sensor.humidity_158d000149c128
      # - sensor.temperature_158d0001149b3c
      # - sensor.temperature_158d000117d37a
      # - sensor.temperature_158d00012d9ad7
      # - sensor.temperature_158d000149c128
      - input_boolean.monster_work
      - input_boolean.monster_home
      - input_boolean.homekit_presense
    exclude_entities:
      - switch.xiaomi_miio_switch
      - switch.reset
      - light.gateway_light
  entity_config:
    switch.water_valve:
      name: Подача воды
    alarm_control_panel.ha_alarm:
      name: Сигнализация

automation:
  - alias: 'Start HomeKit'
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: 00:01:00  # Wait 30 seconds
      - service: homekit.start