#===============================================================================
# Счетчик питьевой воды
# NodeMCU ESP8266
#===============================================================================
substitutions:
  device_name: hallLight
  upper_devicename: HallLight
#===============================================================================  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

# Настройки Wi-Fi
wifi:
  ssid: !secret wifi_24_name
  password: !secret wifi_24_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$upper_devicename Fallback Hotspot"
    password: !secret esphome_captive_pass

captive_portal:


api: # Enable Home Assistant API
  password: !secret esphome_pass
  reboot_timeout: 0s      

ota: 
  password: !secret esphome_pass

web_server:
  port: 80

logger:

#===============================================================================
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes