# ----------- User configutaion ------------------
substitutions:
  devicename: watercontrol
  upper_devicename: Watercontrol
  water_open_pin: D4
  water_close_pin: D3
# ----------- /User configutaion ------------------

# Need to turn off logging because senseair uses uart and have conflicts with logging
logger:

esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini
  libraries:
    - "Bounce2"
  includes:
    - water_counters.h
    
wifi:
  ssid: !secret wifi_24_name
  password: !secret wifi_24_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$upper_devicename Fallback Hotspot"
    password: !secret esphome_captive_pass

captive_portal:

# Enable Home Assistant API
api:
  password: !secret esphome_pass

ota:
  password: !secret esphome_pass

web_server:
  port: 80

#===============================================================================
globals:
 - id: water_state
   type: bool
   restore_value: yes
   initial_value: 'true'

sensor:
  - platform: uptime
    name: "$upper_devicename Uptime"
#------------------------------------------------------------------------------    
  - platform: wifi_signal # Уровень Wi-Fi сигнала положительным числом
    name: "wifi_${devicename}"
    update_interval: 60s 
    filters:
      - lambda: return x * (-1);  
#------------------------------------------------------------------------------    
  - platform: custom
    lambda: |-
      auto my_sensor = new WaterCountersSensor();
      App.register_component(my_sensor);
      return {my_sensor->cold_sensor, my_sensor->hot_sensor};
    sensors:
      - name: "Counter Cold"
        accuracy_decimals: 2
      - name: "Counter Hot"
        accuracy_decimals: 2

#------------------------------------------------------------------------------    
switch:
  - platform: gpio
    pin: 
      number: $water_open_pin
      inverted: yes
    id: water_open
  - platform: gpio
    pin: 
      number: $water_close_pin
      inverted: yes
    id: water_close
  - platform: template
    name: "Water valve"
    icon: "mdi:cup-water"
    lambda: |-
      return id(water_state);
    turn_on_action:
      - switch.turn_on: water_close
      - switch.turn_on: water_open
      - delay: 5s
      - switch.turn_off: water_close
      - switch.turn_off: water_open
      - lambda: 'id(water_state) = true;'
    turn_off_action:
      - switch.turn_on: water_close
      - delay: 5s
      - switch.turn_off: water_close
      - lambda: 'id(water_state) = false;'
#===============================================================================
  - platform: restart # Переключатель перезагрузки устройства
    name: "restart_${devicename}"