FROM mkerix/room-assistant:latest-arm32

#ADD ./python /python
#ADD run.sh /run.sh

#RUN apk update && \
#    apk add libusb-dev python3 build-base && \
#    rm -rf /var/lib/apt/lists/* && \
#    chmod +x /run.sh

#CMD ["/run.sh"]