FROM mkerix/room-assistant:latest

ADD ./python /python
ADD run.sh /run.sh

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/* && \
    chmod +x /run.sh

CMD ["/run.sh"]