FROM node:8.12.0

RUN apt-get update && \
    apt-get install -y bluetooth bluez libbluetooth-dev libudev-dev libusb-1.0-0-dev python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

ADD /room-assistant/package.json /room-assistant/package.json
ADD ./python/main.py /room-assistant/python/main.py
WORKDIR /room-assistant
RUN npm install
RUN npm install --build-from-source=noble@1.9.1,mqtt@2.18.2

ADD room-assistant /room-assistant
ADD run.sh /run.sh

CMD ["/run.sh"]
