sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/mainroom_co2"
    name: mainroom_co2
    unit_of_measurement: "ppm"
    value_template: "{{ value_json.co2 }}"
    json_attributes_topic: "zigbee2mqtt/mainroom_co2"

homeassistant:
  customize:
    sensor.mainroom_co2:
      friendly_name: CO2 Гостиная