mqtt:
  sensor:
    - state_topic: "ZigbeeBD0C/bed_co2"
      name: co2_mainroom_bed
      unit_of_measurement: "ppm"
      value_template: "{{ value_json.co2 }}"
      json_attributes_topic: "ZigbeeBD0C/bed_co2"

homeassistant:
  customize:
    sensor.co2_mainroom_bed:
      friendly_name: CO2 Гостиная Кровать