mqtt:
  switch:
    - name: plug_light_hall
      state_topic: "zigbee2mqtt/plug_light_hall"
      payload_off: "OFF"
      payload_on: "ON"
      value_template: "{{ value_json.state }}"
      command_topic: "zigbee2mqtt/plug_light_hall/set/state"

input_boolean:
  hall_light_control:
    name: Контроль света в прихожей
    initial: on

homeassistant:
  customize:
    switch.plug_light_hall:
      friendly_name: Свет прихожая