mqtt:
  binary_sensor:
    - name: motion_sensor_hall
      state_topic: "ZigbeeBD0C/motion_sensor_hall"
      value_template: "{{ value_json.occupancy }}"
      device_class: occupancy
      off_delay: 10
      payload_on: true
      payload_off: false
      json_attributes_topic: "ZigbeeBD0C/motion_sensor_hall"

homeassistant:
  customize:
    binary_sensor.motion_sensor_hall:
      friendly_name: Движение (холл)