mqtt:
  binary_sensor:
    - name: motion_sensor_bath
      state_topic: "ZigbeeBD0C/motion_sensor_bath"
      value_template: "{{ value_json.occupancy }}"
      device_class: occupancy
      off_delay: 10
      payload_on: true
      payload_off: false
      json_attributes_topic: "ZigbeeBD0C/motion_sensor_bath"

homeassistant:
  customize:
    binary_sensor.motion_sensor_bath:
      friendly_name: Движение (Ванна)