sensor:
  - platform: "mqtt"
    name: "uptime_sls"
    state_topic: "ZigbeeBD0C/bridge/config"
    value_template: "{{ value_json.Uptime }}"

  - platform: "mqtt"
    name: "sls_state"
    state_topic: "ZigbeeBD0C/bridge/state"
    value_template: "{{ value }}"
    json_attributes_topic: "ZigbeeBD0C/bridge/config"

  - platform: "mqtt"
    name: "sls_FreeMem"
    state_topic: "ZigbeeBD0C/bridge/config"
    value_template: "{{ (value_json.FreeMem | int) }}"
    unit_of_measurement: 'b'
  
  - platform: "mqtt"
    name: "sls_Uptime"
    state_topic: "ZigbeeBD0C/bridge/config"
    value_template: "{{ (value_json.Uptime | int) }}"
    unit_of_measurement: 'sec'

  - platform: "mqtt"
    name: "sls_permit_join"
    state_topic: "ZigbeeBD0C/bridge/config"
    value_template: "{{ value_json.permit_join }}"
