mqtt:
  sensor:
    - state_topic: "ZigbeeBD0C/temperature_humidity_bath"
      name: temperature_bath
      unit_of_measurement: "°C"
      device_class: "temperature"
      value_template: "{{ value_json.temperature }}"
      json_attributes_topic: "ZigbeeBD0C/temperature_humidity_bath"
    - name: humidity_bath
      state_topic: "ZigbeeBD0C/temperature_humidity_bath"
      unit_of_measurement: "%"
      device_class: "humidity"
      value_template: "{{ value_json.humidity }}"
      json_attributes_topic: "ZigbeeBD0C/temperature_humidity_bath"

homeassistant:
  customize:
    sensor.temperature_bath:
      friendly_name: Температура (Ванна)
    sensor.humidity_bath:
      friendly_name: Влажность (Ванна)