mqtt:
  sensor:
    - state_topic: "ZigbeeBD0C/temperature_humidity_outside"
      name: temperature_outside
      unit_of_measurement: "°C"
      device_class: "temperature"
      value_template: "{{ value_json.temperature }}"
      json_attributes_topic: "ZigbeeBD0C/temperature_humidity_outside"
    - name: humidity_outside
      state_topic: "ZigbeeBD0C/temperature_humidity_outside"
      unit_of_measurement: "%"
      device_class: "humidity"
      value_template: "{{ value_json.humidity }}"
      json_attributes_topic: "ZigbeeBD0C/temperature_humidity_outside"

homeassistant:
  customize:
    sensor.temperature_outside:
      friendly_name: Температура (улица)
    sensor.humidity_outside:
      friendly_name: Влажность (улица)
