mqtt:
  binary_sensor:
    - name: water_leak_sensor_kitchen_washer
      state_topic: "ZigbeeBD0C/water_leak_sensor_kitchen_washer"
      value_template: "{{ value_json.water_leak }}"
      device_class: moisture
      payload_on: true
      payload_off: false
      json_attributes_topic: "ZigbeeBD0C/water_leak_sensor_kitchen_washer"

homeassistant:
  customize:
    binary_sensor.water_leak_sensor_kitchen_washer:
      friendly_name: Кухня стиралка (протечка)
