mqtt:
  binary_sensor:
    - name: water_leak_sensor_bath_bath
      state_topic: "ZigbeeBD0C/water_leak_sensor_bath_bath"
      value_template: "{{ value_json.water_leak }}"
      device_class: moisture
      payload_on: true
      payload_off: false
      json_attributes_topic: "ZigbeeBD0C/water_leak_sensor_bath_bath"

homeassistant:
  customize:
    binary_sensor.water_leak_sensor_bath_bath:
      friendly_name: Под ванной (протечка)
