sensor:
  #SSL Certificate expire info
  - platform: cert_expiry
    host: !secret base_host
  
  # System resources
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: memory_free
      - type: swap_use_percent
      - type: disk_use_percent
        arg: /
