version: '2'
services:
  rass:
    build:
      context: .
      dockerfile: Dockerfile-rpi
    container_name: rass
    network_mode: host
    volumes:
      - ./local.json:/room-assistant/config/local.json
    # environment:
    #   SERVICES: 'ble,console'
    #   ROOM: 'balcony'
    #   MQTT_URL: 'mqtt://192.168.1.6'
    #   MQTT_USERNAME: 'hass'
    #   MQTT_PASSWORD: 'mqttpass'
    restart: always
