#FROM arm32v7/node
FROM arm32v7/ubuntu

RUN apt-get update && \
    apt-get install -y curl bluetooth bluez libbluetooth-dev libudev-dev libusb-1.0-0-dev python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*


ADD ./python/main.py /room-assistant/python/main.py
ADD /room-assistant/package.json /room-assistant/package.json
WORKDIR /room-assistant
RUN npm install

ADD room-assistant /room-assistant
ADD run.sh /run.sh

CMD ["/run.sh"]
