sensor:
  - platform: mqtt_room
    device_id: !secret tag_danil_keys
    name: tag_danil_keys
    state_topic: home/presence
    timeout: 15
    away_timeout: 60

input_boolean:
  tag_danil_keys:
    name: Данил (Ключи)
    initial: on

homeassistant:
  customize:
    sensor.tag_danil_keys:
      friendly_name: Данил (Ключи)