sensor:
  - platform: mqtt_room
    device_id: !secret tag_test
    name: tag_test
    state_topic: home/presence
    timeout: 15
    away_timeout: 60

input_boolean:
  tag_test:
    name: Тестовая
    initial: on

homeassistant:
  customize:
    sensor.tag_test:
      friendly_name: Тестовая