#################################
#       INVALID AUTH REPORT     #
#################################
invalid_auth_report:
  class: Security
  module: security
  alice: media_player.yandex_station
  notify: telegram
  global_dependencies:
    - globals